channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab
- nodejs
- nbconvert
- widgetsnbextension
# Python Kernel
- ipykernel
- ipywidgets
- ipyleaflet
- altair
- bqplot
- dask
- matplotlib
- pandas
- python
- seaborn
- tensorflow
- sympy
- pyyaml
- traittypes
- invoke

# R Kernel
- r-ggplot2
- r-irkernel
